language: node_js
node_js:
  - 10.6.0
install:
  - npm install -g firebase-tools
  - npm i nuxt
after_success:
  - npm i -g firebase-ci
  - cd functions
  - npm install
  - cd ../
  - npm run generate
  - firebase-ci deploy
branches:
  only:
    - master
script:
  - echo "Deploy"
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
  project: $FIREBASE_PROJECT
